export declare const BOARD_TEXT_FIELDS: string[];
export declare const BOARD_STEP_FIELDS: string[];
export declare const BOARD_CHART_SERIES_FIELDS: string[];
export declare const BOARD_CHART_HAS_LABELS: boolean;
export declare const BOARD_ANNOTATION_FIELDS: string[];
export declare const MESSAGE_FIELDS: string[];
export declare const MEMORY_PLAIN_TO_CIPHER: Record<string, string>;
export declare const TASK_FIELDS: string[];
export declare const COMMENT_FIELDS: string[];
export declare const GOAL_FIELDS: string[];
export declare const SUMMARY_FIELDS: string[];
